[tool.poetry]
name = "dyvy-backend"
version = "0.1.0"
description = "DyvyAI backend"
authors = ["Guro Bokum <jiojiajiu@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.taskipy.tasks]
lint = "ruff format --check . && ruff check --diff"
format = "ruff format"
mypy = "mypy ."

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.5"
pydantic-settings = "^2.7.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.14.1"
ruff = "^0.8.6"
taskipy = "^1.14.1"

# https://mypy.readthedocs.io/en/latest/config_file.html
[tool.mypy]
strict_optional = true
show_error_codes = true
show_column_numbers = true
implicit_reexport = false
disallow_any_unimported = false
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_no_return = true
warn_return_any = true
warn_unused_configs = true
strict_equality = true

# https://docs.astral.sh/ruff/configuration
[tool.ruff]
line-length = 88 # default

[tool.ruff.lint]
extend-select = ["B", "I", "SIM", "UP"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
